// <auto-generated />
namespace BaseType.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ss16 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ss16));
        
        string IMigrationMetadata.Id
        {
            get { return "201503051641485_ss16"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
